---
version: 2
multicolumn: false
web-width: 800
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/fig_gold/fig_gold.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/6245/articles/292763/master/file/figures/fig_gold/fig_gold.png"
    folder_url: "/users/6245/articles/292763/master/folder/figures/fig_gold"
