---
version: 2
multicolumn: false
web-width: 800
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/braindr_xgboost_agg1/braindr_xgboost_agg.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/6245/articles/292763/master/folder/figures/braindr_xgboost_agg1"
    url: "/users/6245/articles/292763/master/file/figures/braindr_xgboost_agg1/braindr_xgboost_agg.png"
